import {writeFile} from 'node:fs/promises';
const key=process.env.API_FOOTBALL_KEY;if(!key)throw new Error('API_FOOTBALL_KEY eksik');
const leagues=[39,61,78,135,140,203],season=new Date().getUTCFullYear();
const median=a=>{const s=[...a].sort((x,y)=>x-y),n=s.length;return n?s[Math.floor((n-1)/2)]:null};
const days=[0,1].map(n=>{const d=new Date(Date.now()+n*86400000);return d.toISOString().slice(0,10)});
const rows=[];
for(const date of days)for(const league of leagues){let page=1,total=1;do{const u=new URL('https://v3.football.api-sports.io/odds');u.searchParams.set('league',league);u.searchParams.set('season',season);u.searchParams.set('date',date);u.searchParams.set('page',page);const r=await fetch(u,{headers:{'x-apisports-key':key}});if(!r.ok)throw new Error(`API ${r.status}`);const j=await r.json();total=j.paging?.total||1;for(const event of j.response||[]){const sets=[];for(const book of event.bookmakers||[]){const bet=book.bets?.find(b=>b.id===1||/match winner/i.test(b.name));if(!bet)continue;const val=n=>Number(bet.values?.find(v=>String(v.value).toLowerCase()===n)?.odd);const one=val('home'),draw=val('draw'),two=val('away');if(one>1&&draw>1&&two>1)sets.push({one,draw,two})}if(!sets.length)continue;const one=median(sets.map(x=>x.one)),draw=median(sets.map(x=>x.draw)),two=median(sets.map(x=>x.two)),raw=[1/one,1/draw,1/two],sum=raw.reduce((a,b)=>a+b,0);rows.push({fixtureId:event.fixture.id,date:event.fixture.date,league:event.league.name,home:event.teams.home.name,away:event.teams.away.name,odds:{home:one,draw,away:two},probabilities:{home:raw[0]/sum,draw:raw[1]/sum,away:raw[2]/sum},bookmakerCount:sets.length,updated:event.update||new Date().toISOString()})}page++}while(page<=total)}
await writeFile('odds-feed.json',JSON.stringify({generatedAt:new Date().toISOString(),matches:rows},null,2)+'\n');
console.log(`${rows.length} maç oranı güncellendi`);
